name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Bun
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2


    # Install Node.js dependencies and build frontend
    - name: Install dependencies and build frontend
      run: |
        bun install
        bun run build

    # Build Go application
    - name: Build Go application
      run: go build -o chrisrock.ca
    # Debugging step to confirm file paths
    - name: List files for debugging
      run: |
        ls -la static/css
        ls -la static/js
        ls -la chrisrock.ca
    # Deploy to VPS via SSH
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: 22
        script: |
          mkdir -p /var/www/chrisrock.ca/static/css
          mkdir -p /var/www/chrisrock.ca/static/js

        
          echo "Deploying compiled CSS..."
          if [ -f ./static/css/output.css ]; then
            rm -f /var/www/chrisrock.ca/static/css/output.css
            mv ./static/css/output.css /var/www/chrisrock.ca/static/css/output.css
          else
            echo "CSS file not found!"
          fi

          echo "Deploying compiled JS..."
          if [ -d ./static/js ]; then
            rm -rf /var/www/chrisrock.ca/static/js
            mv ./static/js /var/www/chrisrock.ca/static/js
          else
            echo "JS directory not found!"
          fi

          echo "Deploying Go application..."
          if [ -f ./chrisrock.ca ]; then
            rm -f /var/www/chrisrock.ca/chrisrock.ca
            mv ./chrisrock.ca /var/www/chrisrock.ca/chrisrock.ca
            chmod +x /var/www/chrisrock.ca/chrisrock.ca
          else
            echo "Go application not found!"
          fi

          systemctl restart chrisrock.ca.service
          