name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Bun
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2

    # Install Node.js dependencies and build frontend
    - name: Install dependencies and build frontend
      run: |
        bun install
        bun run build

    # Build Go application
    - name: Build Go application
      run: go build -o chrisrock.ca
    # Transfer files to VPS via SCP
    - name: Transfer files to server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: 22
        source: static/compiled/*
        target: /tmp/compiled

    # Deploy to VPS via SSH
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Creating directories on server..."
          sudo mkdir -p /var/www/chrisrock.ca/static/css
          sudo mkdir -p /var/www/chrisrock.ca/static/js

          echo "Deploying compiled JS & CSS..."
          if [ -d /tmp/compiled ]; then
            rm -rf /var/www/chrisrock.ca/static/compiled
            mv /tmp/compiled /var/www/chrisrock.ca/static/compiled
          else
            echo "CSS file not found!"
          fi

          echo "Deploying Go application..."
          if [ -f /tmp/chrisrock.ca ]; then
            mv /tmp/chrisrock.ca /var/www/chrisrock.ca/chrisrock.ca
            sudo chmod +x /var/www/chrisrock.ca/chrisrock.ca
          else
            echo "Go application not found!"
          fi

          echo "Listing /var/www/chrisrock.ca directory on server..."
          ls -la /var/www/chrisrock.ca

          echo "Restarting service with sudo..."
          sudo systemctl restart chrisrock.ca.service
